export default new Map<string, any>([
  [
    "1",
    {
      metagame_event_id: "1",
      name: {
        de: "Spüre die Hitze",
        en: "Feeling the Heat",
        es: "Siente el calor",
        fr: "Sentir la pression",
        it: "Sotto pressione",
        tr: "Sıcağı Hissetmek",
      },
      description: {
        de: "Erobere Indar innerhalb des Zeitlimits.",
        en: "Capture Indar within the time limit",
        es: "Captura Indar sin pasarte del límite de tiempo",
        fr: "Capturer Indar dans la limite de temps",
        it: "Conquista Indar nei limiti di tempo",
        tr: "Zaman sınırı içinde Indar'ı Ele Geçir",
      },
      type: "1",
      experience_bonus: "30",
    },
  ],
  [
    "2",
    {
      metagame_event_id: "2",
      name: {
        de: "Kalter Krieg",
        en: "Cold War",
        es: "Guerra fría",
        fr: "Guerre froide",
        it: "Guerra fredda",
        tr: "Soğuk Savaş",
      },
      description: {
        de: "Erobere Esamir innerhalb des Zeitlimits.",
        en: "Capture Esamir within the time limit",
        es: "Captura Esamir sin pasarte del límite de tiempo",
        fr: "Capturer Esamir dans la limite de temps",
        it: "Conquista Esamir nei limiti di tempo",
        tr: "Zaman sınırı içinde Esamir'i El Geçir",
      },
      type: "1",
      experience_bonus: "30",
    },
  ],
  [
    "3",
    {
      metagame_event_id: "3",
      name: {
        de: "Grün sehen",
        en: "Seeing Green",
        es: "Ver en verde",
        fr: "Voir vert",
        it: "Vedo verde",
        tr: "Yeşil Görme",
      },
      description: {
        de: "Erobere Amerish innerhalb des Zeitlimits.",
        en: "Capture Amerish within the time limit",
        es: "Captura Amerish sin pasarte del límite de tiempo",
        fr: "Capturer Amerish dans la limite de temps",
        it: "Conquista Amerish nei limiti di tempo",
        tr: "Zaman sınırı içinde Amerish'i Ele Geçir",
      },
      type: "1",
      experience_bonus: "30",
    },
  ],
  [
    "4",
    {
      metagame_event_id: "4",
      name: {
        de: "Marsh Madness",
        en: "Marsh Madness",
        es: "Marsh Madness",
        fr: "Marsh Madness",
        it: "Marsh Madness",
        tr: "Marsh Madness",
      },
      description: {
        de: "Erobere Hossin innerhalb des Zeitlimits.",
        en: "Capture Hossin within the time limit",
        es: "Captura Hossin sin pasarte del límite de tiempo",
        fr: "Capturer Hossin dans la limite de temps",
        it: "Conquista Hossin nei limiti di tempo",
        tr: "Capture Hossin within the time limit",
      },
      type: "1",
      experience_bonus: "30",
    },
  ],
  [
    "7",
    {
      metagame_event_id: "7",
      name: {
        de: "Dom-Herrschaft",
        en: "Dome Domination",
        es: "Dominio de cúpula",
        fr: "Domination du Dôme",
        it: "Dominio della cupola",
        tr: "Dome Domination",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Biolaboren auf Amerish.",
        en: "Capture and hold all 3 Biolabs on Amerish",
        es: "Conquista 3 Biolabs en Amerish y mantén el control",
        fr: "Capturer et garder les 3 Biolabs sur Amerish",
        it: "Conquista e difendi tutti e 3 i Biolab di Amerish",
        tr: "Capture and hold all 3 Biolabs on Amerish",
      },
      type: "2",
    },
  ],
  [
    "8",
    {
      metagame_event_id: "8",
      name: {
        de: "Technologischer Fortschritt",
        en: "Technological Advancement",
        es: "Avance tecnológico",
        fr: "Évolution technologique",
        it: "Progresso tecnologico",
        tr: "Technological Advancement",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Technikanlagen auf Amerish.",
        en: "Capture and hold all 3 Tech Plants on Amerish",
        es: "Conquista 3 Tech Plants en Amerish y mantén el control",
        fr: "Capturer et garder les 3 Tech Plants sur Amerish",
        it: "Conquista e difendi tutti e 3 i Tech Plant di Amerish",
        tr: "Capture and hold all 3 Tech Plants on Amerish",
      },
      type: "2",
    },
  ],
  [
    "9",
    {
      metagame_event_id: "9",
      name: {
        de: "Machtrausch",
        en: "Power Rush",
        es: "Avalancha de poder",
        fr: "Accéleration de pouvoir",
        it: "Corsa al potere",
        tr: "Power Rush",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Verstärker-Stationen auf Amerish.",
        en: "Capture and hold all 3 Amp Stations on Amerish",
        es: "Conquista 3 Amp Stations en Amerish y mantén el control",
        fr: "Capturer et garder les 3 Amp Stations sur Amerish",
        it: "Conquista e difendi tutte e 3 le Amp Station di Amerish",
        tr: "Capture and hold all 3 Amp Stations on Amerish",
      },
      type: "2",
    },
  ],
  [
    "10",
    {
      metagame_event_id: "10",
      name: {
        de: "Dom-Herrschaft",
        en: "Dome Domination",
        es: "Dominio de cúpula",
        fr: "Domination du Dôme",
        it: "Dominio della cupola",
        tr: "Dome Domination",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Biolaboren auf Indar.",
        en: "Capture and hold all 3 Biolabs on Indar",
        es: "Conquista 3 Biolabs en Indar y mantén el control",
        fr: "Capturer et garder les 3 Biolabs sur Indar",
        it: "Conquista e difendi tutti e 3 i Biolab di Indar",
        tr: "Capture and hold all 3 Biolabs on Indar",
      },
      type: "2",
    },
  ],
  [
    "11",
    {
      metagame_event_id: "11",
      name: {
        de: "Technologischer Fortschritt",
        en: "Technological Advancement",
        es: "Avance tecnológico",
        fr: "Évolution technologique",
        it: "Progresso tecnologico",
        tr: "Technological Advancement",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Technikanlagen auf Indar.",
        en: "Capture and hold all 3 Tech Plants on Indar",
        es: "Conquista 3 Tech Plants en Indar y mantén el control",
        fr: "Capturer et garder les 3 Tech Plants sur Indar",
        it: "Conquista e difendi tutti e 3 i Tech Plant di Indar",
        tr: "Capture and hold all 3 Tech Plants on Indar",
      },
      type: "2",
    },
  ],
  [
    "12",
    {
      metagame_event_id: "12",
      name: {
        de: "Machtrausch",
        en: "Power Rush",
        es: "Avalancha de poder",
        fr: "Accéleration de pouvoir",
        it: "Corsa al potere",
        tr: "Power Rush",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Verstärker-Stationen auf Indar.",
        en: "Capture and hold all 3 Amp Stations on Indar",
        es: "Conquista 3 Amp Stations en Indar y mantén el control",
        fr: "Capturer et garder les 3 Amp Stations sur Indar",
        it: "Conquista e difendi tutte e 3 le Amp Station di Indar",
        tr: "Capture and hold all 3 Amp Stations on Indar",
      },
      type: "2",
    },
  ],
  [
    "13",
    {
      metagame_event_id: "13",
      name: {
        de: "Dom-Herrschaft",
        en: "Dome Domination",
        es: "Dominio de cúpula",
        fr: "Domination du Dôme",
        it: "Dominio della cupola",
        tr: "Dome Domination",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Biolaboren auf Esamir.",
        en: "Capture and hold all 3 Biolabs on Esamir",
        es: "Conquista 3 Biolabs en Esamir y mantén el control",
        fr: "Capturer et garder les 3 Biolabs sur Esamir",
        it: "Conquista e difendi tutti e 3 i Biolab di Esamir",
        tr: "Capture and hold all 3 Biolabs on Esamir",
      },
      type: "2",
    },
  ],
  [
    "14",
    {
      metagame_event_id: "14",
      name: {
        de: "Machtrausch",
        en: "Power Rush",
        es: "Avalancha de poder",
        fr: "Accéleration de pouvoir",
        it: "Corsa al potere",
        tr: "Power Rush",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Verstärker-Stationen auf Esamir.",
        en: "Capture and hold all 3 Amp Stations on Esamir",
        es: "Conquista 3 Amp Stations en Esamir y mantén el control",
        fr: "Capturer et garder les 3 Amp Stations sur Esamir",
        it: "Conquista e difendi tutte e 3 le Amp Station di Esamir",
        tr: "Capture and hold all 3 Amp Stations on Esamir",
      },
      type: "2",
    },
  ],
  [
    "16",
    {
      metagame_event_id: "16",
      name: {
        de: "Dom-Herrschaft",
        en: "Dome Domination",
        es: "Dominio de cúpula",
        fr: "Domination du Dôme",
        it: "Dominio della cupola",
        tr: "Dome Domination",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Biolaboren auf Hossin.",
        en: "Capture and hold all 3 Biolabs on Hossin",
        es: "Conquista 3 Biolabs en Hossin y mantén el control",
        fr: "Capturer et garder les 3 Biolabs sur Hossin",
        it: "Conquista e difendi tutti e 3 i Biolab di Hossin",
        tr: "Capture and hold all 3 Biolabs on Hossin",
      },
      type: "2",
    },
  ],
  [
    "17",
    {
      metagame_event_id: "17",
      name: {
        de: "Technologischer Fortschritt",
        en: "Technological Advancement",
        es: "Avance tecnológico",
        fr: "Évolution technologique",
        it: "Progresso tecnologico",
        tr: "Technological Advancement",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Technikanlagen auf Hossin.",
        en: "Capture and hold all 3 Tech Plants on Hossin",
        es: "Conquista 3 Tech Plants en Hossin y mantén el control",
        fr: "Capturer et garder les 3 Tech Plants sur Hossin",
        it: "Conquista e difendi tutti e 3 i Tech Plant di Hossin",
        tr: "Capture and hold all 3 Tech Plants on Hossin",
      },
      type: "2",
    },
  ],
  [
    "18",
    {
      metagame_event_id: "18",
      name: {
        de: "Machtrausch",
        en: "Power Rush",
        es: "Avalancha de poder",
        fr: "Accéleration de pouvoir",
        it: "Corsa al potere",
        tr: "Power Rush",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Verstärker-Stationen auf Hossin.",
        en: "Capture and hold all 3 Amp Stations on Hossin",
        es: "Conquista 3 Amp Stations en Hossin y mantén el control",
        fr: "Capturer et garder les 3 Amp Stations sur Hossin",
        it: "Conquista e difendi tutte e 3 le Amp Station di Hossin",
        tr: "Capture and hold all 3 Amp Stations on Hossin",
      },
      type: "2",
    },
  ],
  [
    "106",
    {
      metagame_event_id: "106",
      name: { de: "Eroberung", en: "Conquest", es: "Conquista", fr: "Conquête", it: "Conquista" },
      description: {
        de: "Erobere Basen und töte Feinde, um Punkte zu erhalten.",
        en: "Capture bases and kill enemies to earn points.",
        es: "Captura bases y acaba con los enemigos para conseguir puntos.",
        fr: "Capturer des bases et tuer des ennemis afin de remporter des points.",
        it: "Conquista le basi e uccidi i nemici per accumulare punti.",
      },
      type: "6",
    },
  ],
  [
    "123",
    {
      metagame_event_id: "123",
      name: {
        de: "Überlegenheit von Indar",
        en: "Indar Superiority",
        es: "Supremacía en Indar",
        fr: "Supériorité d'Indar",
        it: "Superiorità di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "124",
    {
      metagame_event_id: "124",
      name: {
        de: "Erleuchtung von Indar",
        en: "Indar Enlightenment",
        es: "Iluminación de Indar",
        fr: "Savoir d'Indar",
        it: "Risveglio di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "125",
    {
      metagame_event_id: "125",
      name: {
        de: "Befreiung von Indar",
        en: "Indar Liberation",
        es: "Liberación de Indar",
        fr: "Libération d'Indar",
        it: "Liberazione di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "126",
    {
      metagame_event_id: "126",
      name: {
        de: "Überlegenheit von Esamir",
        en: "Esamir Superiority",
        es: "Superioridad en Esamir",
        fr: "Supériorité d'Esamir",
        it: "Superiorità di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "127",
    {
      metagame_event_id: "127",
      name: {
        de: "Erleuchtung von Esamir",
        en: "Esamir Enlightenment",
        es: "Iluminación de Esamir",
        fr: "Savoir d'Esamir",
        it: "Risveglio di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "128",
    {
      metagame_event_id: "128",
      name: {
        de: "Befreiung von Esamir",
        en: "Esamir Liberation",
        es: "Liberación de Esamir",
        fr: "Libération d'Esamir",
        it: "Liberazione di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "129",
    {
      metagame_event_id: "129",
      name: {
        de: "Überlegenheit von Hossin",
        en: "Hossin Superiority",
        es: "Superioridad de Hossin",
        fr: "Supériorité d'Hossin",
        it: "Superiorità di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "130",
    {
      metagame_event_id: "130",
      name: {
        de: "Erleuchtung von Hossin",
        en: "Hossin Enlightenment",
        es: "Iluminación de Hossin",
        fr: "Savoir d'Hossin",
        it: "Risveglio di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "131",
    {
      metagame_event_id: "131",
      name: {
        de: "Befreiung von Hossin",
        en: "Hossin Liberation",
        es: "Liberación de Hossin",
        fr: "Libération d'Hossin",
        it: "Liberazione di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "132",
    {
      metagame_event_id: "132",
      name: {
        de: "Überlegenheit von Amerish",
        en: "Amerish Superiority",
        es: "Superioridad de Amerish",
        fr: "Supériorité d'Amerish",
        it: "Superiorità di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "133",
    {
      metagame_event_id: "133",
      name: {
        de: "Erleuchtung von Amerish",
        en: "Amerish Enlightenment",
        es: "Iluminación de Amerish",
        fr: "Savoir d'Amerish",
        it: "Risveglio di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "134",
    {
      metagame_event_id: "134",
      name: {
        de: "Befreiung von Amerish",
        en: "Amerish Liberation",
        es: "Liberación de Amerish",
        fr: "Libération d'Amerish",
        it: "Liberazione di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "8",
      experience_bonus: "30",
    },
  ],
  [
    "147",
    {
      metagame_event_id: "147",
      name: {
        de: "Überlegenheit von Indar",
        en: "Indar Superiority",
        es: "Supremacía en Indar",
        fr: "Supériorité d'Indar",
        it: "Superiorità di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "148",
    {
      metagame_event_id: "148",
      name: {
        de: "Erleuchtung von Indar",
        en: "Indar Enlightenment",
        es: "Iluminación de Indar",
        fr: "Savoir d'Indar",
        it: "Risveglio di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "149",
    {
      metagame_event_id: "149",
      name: {
        de: "Befreiung von Indar",
        en: "Indar Liberation",
        es: "Liberación de Indar",
        fr: "Libération d'Indar",
        it: "Liberazione di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "150",
    {
      metagame_event_id: "150",
      name: {
        de: "Überlegenheit von Esamir",
        en: "Esamir Superiority",
        es: "Superioridad en Esamir",
        fr: "Supériorité d'Esamir",
        it: "Superiorità di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "151",
    {
      metagame_event_id: "151",
      name: {
        de: "Erleuchtung von Esamir",
        en: "Esamir Enlightenment",
        es: "Iluminación de Esamir",
        fr: "Savoir d'Esamir",
        it: "Risveglio di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "152",
    {
      metagame_event_id: "152",
      name: {
        de: "Befreiung von Esamir",
        en: "Esamir Liberation",
        es: "Liberación de Esamir",
        fr: "Libération d'Esamir",
        it: "Liberazione di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "153",
    {
      metagame_event_id: "153",
      name: {
        de: "Überlegenheit von Hossin",
        en: "Hossin Superiority",
        es: "Superioridad de Hossin",
        fr: "Supériorité d'Hossin",
        it: "Superiorità di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "154",
    {
      metagame_event_id: "154",
      name: {
        de: "Erleuchtung von Hossin",
        en: "Hossin Enlightenment",
        es: "Iluminación de Hossin",
        fr: "Savoir d'Hossin",
        it: "Risveglio di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "155",
    {
      metagame_event_id: "155",
      name: {
        de: "Befreiung von Hossin",
        en: "Hossin Liberation",
        es: "Liberación de Hossin",
        fr: "Libération d'Hossin",
        it: "Liberazione di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "156",
    {
      metagame_event_id: "156",
      name: {
        de: "Überlegenheit von Amerish",
        en: "Amerish Superiority",
        es: "Superioridad de Amerish",
        fr: "Supériorité d'Amerish",
        it: "Superiorità di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "157",
    {
      metagame_event_id: "157",
      name: {
        de: "Erleuchtung von Amerish",
        en: "Amerish Enlightenment",
        es: "Iluminación de Amerish",
        fr: "Savoir d'Amerish",
        it: "Risveglio di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "158",
    {
      metagame_event_id: "158",
      name: {
        de: "Befreiung von Amerish",
        en: "Amerish Liberation",
        es: "Liberación de Amerish",
        fr: "Libération d'Amerish",
        it: "Liberazione di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "159",
    {
      metagame_event_id: "159",
      name: {
        de: "Warptore in Amerish stabilisieren sich",
        en: "Amerish Warpgates Stabilizing",
        es: "Warpgates de Amerish estabilizándose",
        fr: "Warpgates d'Amerish en cours de stabilisation",
        it: "Stabilizzazione dei Warpgate di Amerish",
      },
      description: {
        de: "Zusätzliche Territorien gehen wieder online.",
        en: "Additional territories are coming back online.",
        es: "Más territorios se están reactivando.",
        fr: "Des territoires supplémentaires reviennent en ligne.",
        it: "Altri territori si stanno riattivando.",
      },
      type: "5",
    },
  ],
  [
    "160",
    {
      metagame_event_id: "160",
      name: {
        de: "Warptore in Esamir stabilisieren sich",
        en: "Esamir Warpgates Stabilizing",
        es: "Warpgates de Esamir estabilizándose",
        fr: "Warpgates d'Esamir en cours de stabilisation",
        it: "Stabilizzazione dei Warpgate di Esamir",
      },
      description: {
        de: "Zusätzliche Territorien gehen wieder online.",
        en: "Additional territories are coming back online.",
        es: "Más territorios se están reactivando.",
        fr: "Des territoires supplémentaires reviennent en ligne.",
        it: "Altri territori si stanno riattivando.",
      },
      type: "5",
    },
  ],
  [
    "161",
    {
      metagame_event_id: "161",
      name: {
        de: "Warptore in Indar stabilisieren sich",
        en: "Indar Warpgates Stabilizing",
        es: "Warpgates de Indar estabilizándose",
        fr: "Warpgates d'Indar en cours de stabilisation",
        it: "Stabilizzazione dei Warpgate di Indar",
      },
      description: {
        de: "Zusätzliche Territorien gehen wieder online.",
        en: "Additional territories are coming back online.",
        es: "Más territorios se están reactivando.",
        fr: "Des territoires supplémentaires reviennent en ligne.",
        it: "Altri territori si stanno riattivando.",
      },
      type: "5",
    },
  ],
  [
    "162",
    {
      metagame_event_id: "162",
      name: {
        de: "Warptore in Hossin stabilisieren sich",
        en: "Hossin Warpgates Stabilizing",
        es: "Warpgates de Hossin estabilizándose",
        fr: "Warpgates de Hossin en cours de stabilisation",
        it: "Stabilizzazione dei Warpgate di Hossin",
      },
      description: {
        de: "Zusätzliche Territorien gehen wieder online.",
        en: "Additional territories are coming back online.",
        es: "Más territorios se están reactivando.",
        fr: "Des territoires supplémentaires reviennent en ligne.",
        it: "Altri territori si stanno riattivando.",
      },
      type: "5",
    },
  ],
  [
    "164",
    {
      metagame_event_id: "164",
      name: {
        de: "Technologischer Fortschritt",
        en: "Technological Advancement",
        es: "Avance tecnológico",
        fr: "Évolution technologique",
        it: "Progresso tecnologico",
        tr: "Technological Advancement",
      },
      description: {
        de: "Erobere und halte Stellung bei allen 3 Technikanlagen auf Esamir.",
        en: "Capture and hold all 3 Tech Plants on Esamir",
        es: "Conquista 3 Tech Plants en Esamir y mantén el control",
        fr: "Capturer et garder les 3 Tech Plants sur Esamir",
        it: "Conquista e difendi tutti e 3 i Tech Plant di Esamir",
        tr: "Capture and hold all 3 Tech Plants on Esamir",
      },
      type: "2",
    },
  ],
  [
    "167",
    {
      metagame_event_id: "167",
      name: {
        de: "Anomalien im Luftbereich",
        en: "Aerial Anomalies",
        es: "Anomalías aéreas",
        fr: "Anomalies Aériennes",
        it: "Anomalie aeree",
      },
      description: {
        de: "Mache Aufzeichnungen der Anomalien im Luftbereich.",
        en: "Take readings of aerial anomalies",
        es: "Obtén mediciones de las anomalías aéreas.",
        fr: "Effectuez des relevés des anomalies aériennes",
        it: "Effettua i rilevamenti delle anomalie aeree",
      },
      type: "10",
    },
  ],
  [
    "168",
    {
      metagame_event_id: "168",
      name: {
        de: "Auge des Sturms",
        en: "Eye of the Storm",
        es: "Ojo del huracán",
        fr: "L'Oeil de la Tempête",
        it: "Occhio del ciclone",
      },
      description: {
        de: "Sammle Tempest an der Meteor-Einschlagsstelle und bringe es zu deinem Warptor.",
        en: "Gather Tempest from the meteor site and return it to your Warpgate.",
        es: "Consigue Tempest del lugar del impacto de meteoro y llévalo a tu Warpgate.",
        fr: "Récupérez de la Tempête au site de la météorite et ramenez-la à votre Warpgate",
        it: "Raccogli la bufera dal sito della meteorite e riportala al tuo warpgate.",
      },
      type: "10",
    },
  ],
  [
    "170",
    {
      metagame_event_id: "170",
      name: {
        de: "The Bending",
        en: "The Bending",
        es: "The Bending",
        fr: "La Distorsion",
        it: "Bending",
      },
      description: {
        de: "Ein tödlicher Meteor-Schauer verursacht Chaos auf dem Kontinent.",
        en: "A deadly meteor shower is wreaking havoc across the continent.",
        es: "Una peligrosa lluvia de meteoritos está desatando el caos en el continente.",
        fr: "Une pluie de météorites dévastatrices ravage le continent.",
        it: "Una letale pioggia di meteoriti sta portando distruzione sul continente.",
      },
      type: "5",
    },
  ],
  [
    "172",
    {
      metagame_event_id: "172",
      name: {
        de: "Anomalien im Luftbereich",
        en: "Aerial Anomalies",
        es: "Anomalías aéreas",
        fr: "Anomalies Aériennes",
        it: "Anomalie aeree",
      },
      description: {
        de: "Mache Aufzeichnungen der Anomalien im Luftbereich.",
        en: "Take readings of aerial anomalies",
        es: "Obtén mediciones de las anomalías aéreas.",
        fr: "Effectuez des relevés des anomalies aériennes",
        it: "Effettua i rilevamenti delle anomalie aeree",
      },
      type: "10",
    },
  ],
  [
    "173",
    {
      metagame_event_id: "173",
      name: {
        de: "Anomalien im Luftbereich",
        en: "Aerial Anomalies",
        es: "Anomalías aéreas",
        fr: "Anomalies Aériennes",
        it: "Anomalie aeree",
      },
      description: {
        de: "Mache Aufzeichnungen der Anomalien im Luftbereich.",
        en: "Take readings of aerial anomalies",
        es: "Obtén mediciones de las anomalías aéreas.",
        fr: "Effectuez des relevés des anomalies aériennes",
        it: "Effettua i rilevamenti delle anomalie aeree",
      },
      type: "10",
    },
  ],
  [
    "174",
    {
      metagame_event_id: "174",
      name: {
        de: "Anomalien im Luftbereich",
        en: "Aerial Anomalies",
        es: "Anomalías aéreas",
        fr: "Anomalies Aériennes",
        it: "Anomalie aeree",
      },
      description: {
        de: "Mache Aufzeichnungen der Anomalien im Luftbereich.",
        en: "Take readings of aerial anomalies",
        es: "Obtén mediciones de las anomalías aéreas.",
        fr: "Effectuez des relevés des anomalies aériennes",
        it: "Effettua i rilevamenti delle anomalie aeree",
      },
      type: "10",
    },
  ],
  [
    "175",
    {
      metagame_event_id: "175",
      name: {
        de: "Rennen um Messwerte",
        en: "Race for Readings",
        es: "Carrera de mediciones",
        fr: "Course aux relevés",
        it: "Gara per i rilevamenti",
      },
      description: {
        de: "Mache Aufzeichnungen der Anomalien im Luftbereich.",
        en: "Take readings of aerial anomalies",
        es: "Obtén mediciones de las anomalías aéreas.",
        fr: "Effectuez des relevés des anomalies aériennes",
        it: "Effettua i rilevamenti delle anomalie aeree",
      },
      type: "10",
    },
  ],
  [
    "176",
    {
      metagame_event_id: "176",
      name: {
        de: "Esamir - Instabiler Zusammenbruch",
        en: "Esamir Unstable Meltdown",
        es: "Fusión inestable de Esamir",
        fr: "Fusion instable d'Esamir",
        it: "Fusione instabile di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "177",
    {
      metagame_event_id: "177",
      name: {
        de: "Hossin - Instabiler Zusammenbruch",
        en: "Hossin Unstable Meltdown",
        es: "Fusión inestable de Hossin",
        fr: "Fusion instable de Hossin",
        it: "Fusione instabile di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "178",
    {
      metagame_event_id: "178",
      name: {
        de: "Amerish - Instabiler Zusammenbruch",
        en: "Amerish Unstable Meltdown",
        es: "Fusión inestable de Amerish",
        fr: "Fusion instable d'Amerish",
        it: "Fusione instabile di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "179",
    {
      metagame_event_id: "179",
      name: {
        de: "Indar - Instabiler Zusammenbruch",
        en: "Indar Unstable Meltdown",
        es: "Fusión inestable de Indar",
        fr: "Fusion instable d'Indar",
        it: "Fusione instabile di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "180",
    {
      metagame_event_id: "180",
      name: {
        de: "Oberhand",
        en: "Gaining Ground",
        es: "Ganando terreno",
        fr: "Expansion de territoire",
        it: "Guadagnare terreno",
      },
      description: {
        de: "Erobere und halte die meisten großen Außenposten.",
        en: "Capture and hold the most Large Outposts",
        es: "Captura y defiende más puestos de avanzada grandes que nadie.",
        fr: "Capturez et tenez le plus de grands avant-postes",
        it: "Conquista e difendi i più grand avamposti",
      },
      type: "2",
    },
  ],
  [
    "181",
    {
      metagame_event_id: "181",
      name: {
        de: "Oberhand",
        en: "Gaining Ground",
        es: "Ganando terreno",
        fr: "Expansion de territoire",
        it: "Guadagnare terreno",
      },
      description: {
        de: "Erobere und halte die meisten großen Außenposten.",
        en: "Capture and hold the most Large Outposts",
        es: "Captura y defiende más puestos de avanzada grandes que nadie.",
        fr: "Capturez et tenez le plus de grands avant-postes",
        it: "Conquista e difendi i più grand avamposti",
      },
      type: "2",
    },
  ],
  [
    "182",
    {
      metagame_event_id: "182",
      name: {
        de: "Oberhand",
        en: "Gaining Ground",
        es: "Ganando terreno",
        fr: "Expansion de territoire",
        it: "Guadagnare terreno",
      },
      description: {
        de: "Erobere und halte die meisten großen Außenposten.",
        en: "Capture and hold the most Large Outposts",
        es: "Captura y defiende más puestos de avanzada grandes que nadie.",
        fr: "Capturez et tenez le plus de grands avant-postes",
        it: "Conquista e difendi i più grand avamposti",
      },
      type: "2",
    },
  ],
  [
    "183",
    {
      metagame_event_id: "183",
      name: {
        de: "Oberhand",
        en: "Gaining Ground",
        es: "Ganando terreno",
        fr: "Expansion de territoire",
        it: "Guadagnare terreno",
      },
      description: {
        de: "Erobere und halte die meisten großen Außenposten.",
        en: "Capture and hold the most Large Outposts",
        es: "Captura y defiende más puestos de avanzada grandes que nadie.",
        fr: "Capturez et tenez le plus de grands avant-postes",
        it: "Conquista e difendi i più grand avamposti",
      },
      type: "2",
    },
  ],
  [
    "186",
    {
      metagame_event_id: "186",
      name: {
        de: "Esamir - Instabiler Zusammenbruch",
        en: "Esamir Unstable Meltdown",
        es: "Fusión inestable de Esamir",
        fr: "Fusion instable d'Esamir",
        it: "Fusione instabile di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "187",
    {
      metagame_event_id: "187",
      name: {
        de: "Hossin - Instabiler Zusammenbruch",
        en: "Hossin Unstable Meltdown",
        es: "Fusión inestable de Hossin",
        fr: "Fusion instable de Hossin",
        it: "Fusione instabile di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "188",
    {
      metagame_event_id: "188",
      name: {
        de: "Amerish - Instabiler Zusammenbruch",
        en: "Amerish Unstable Meltdown",
        es: "Fusión inestable de Amerish",
        fr: "Fusion instable d'Amerish",
        it: "Fusione instabile di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "189",
    {
      metagame_event_id: "189",
      name: {
        de: "Indar - Instabiler Zusammenbruch",
        en: "Indar Unstable Meltdown",
        es: "Fusión inestable de Indar",
        fr: "Fusion instable d'Indar",
        it: "Fusione instabile di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "190",
    {
      metagame_event_id: "190",
      name: {
        de: "Esamir - Instabiler Zusammenbruch",
        en: "Esamir Unstable Meltdown",
        es: "Fusión inestable de Esamir",
        fr: "Fusion instable d'Esamir",
        it: "Fusione instabile di Esamir",
      },
      description: {
        de: "Kontrolliere das Territorium, um Esamir zu sperren.",
        en: "Control territory to lock Esamir",
        es: "Control del territorio para bloquear Esamir",
        fr: "Contrôlez du territoire pour verrouiller Esamir",
        it: "Controlla il territorio per bloccare Esamir",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "191",
    {
      metagame_event_id: "191",
      name: {
        de: "Hossin - Instabiler Zusammenbruch",
        en: "Hossin Unstable Meltdown",
        es: "Fusión inestable de Hossin",
        fr: "Fusion instable de Hossin",
        it: "Fusione instabile di Hossin",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Hossin zu sperren.",
        en: "Control territory to lock Hossin",
        es: "Control del territorio para bloquear Hossin",
        fr: "Contrôlez du territoire pour verrouiller Hossin",
        it: "Controlla il territorio per bloccare Hossin",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "192",
    {
      metagame_event_id: "192",
      name: {
        de: "Amerish - Instabiler Zusammenbruch",
        en: "Amerish Unstable Meltdown",
        es: "Fusión inestable de Amerish",
        fr: "Fusion instable d'Amerish",
        it: "Fusione instabile di Amerish",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Amerish zu sperren.",
        en: "Control territory to lock Amerish",
        es: "Control del territorio para bloquear Amerish",
        fr: "Contrôlez du territoire pour verrouiller Amerish",
        it: "Controlla il territorio per bloccare Amerish",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "193",
    {
      metagame_event_id: "193",
      name: {
        de: "Indar - Instabiler Zusammenbruch",
        en: "Indar Unstable Meltdown",
        es: "Fusión inestable de Indar",
        fr: "Fusion instable d'Indar",
        it: "Fusione instabile di Indar",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Indar zu sperren.",
        en: "Control territory to lock Indar",
        es: "Control del territorio para bloquear Indar",
        fr: "Contrôlez du territoire pour verrouiller Indar",
        it: "Controlla il territorio per bloccare Indar",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "194",
    {
      metagame_event_id: "194",
      name: {
        de: "Verfeinern und Tanken",
        en: "Refine and Refuel",
        es: "Refinar y repostar",
        fr: "Raffinage et Avitaillement",
        it: "Raffina e rifornisci",
      },
      description: {
        de: "Deponiere Kortium in der Raffinerie.",
        en: "Deposit Cortium into the refinery",
        es: "Deposita cortium en la refinería.",
        fr: "Déposez du Cortium dans la raffinerie",
        it: "Deposita il Cortium nella raffineria",
      },
      type: "10",
    },
  ],
  [
    "195",
    {
      metagame_event_id: "195",
      name: {
        de: "Verfeinern und Tanken",
        en: "Refine and Refuel",
        es: "Refinar y repostar",
        fr: "Raffinage et Avitaillement",
        it: "Raffina e rifornisci",
      },
      description: {
        de: "Deponiere Kortium in der Raffinerie.",
        en: "Deposit Cortium into the refinery",
        es: "Deposita cortium en la refinería.",
        fr: "Déposez du Cortium dans la raffinerie",
        it: "Deposita il Cortium nella raffineria",
      },
      type: "10",
    },
  ],
  [
    "196",
    {
      metagame_event_id: "196",
      name: {
        de: "Verfeinern und Tanken",
        en: "Refine and Refuel",
        es: "Refinar y repostar",
        fr: "Raffinage et Avitaillement",
        it: "Raffina e rifornisci",
      },
      description: {
        de: "Deponiere Kortium in der Raffinerie.",
        en: "Deposit Cortium into the refinery",
        es: "Deposita cortium en la refinería.",
        fr: "Déposez du Cortium dans la raffinerie",
        it: "Deposita il Cortium nella raffineria",
      },
      type: "10",
    },
  ],
  [
    "197",
    {
      metagame_event_id: "197",
      name: {
        de: "Verfeinern und Tanken",
        en: "Refine and Refuel",
        es: "Refinar y repostar",
        fr: "Raffinage et Avitaillement",
        it: "Raffina e rifornisci",
      },
      description: {
        de: "Deponiere Kortium in der Raffinerie.",
        en: "Deposit Cortium into the refinery",
        es: "Deposita cortium en la refinería.",
        fr: "Déposez du Cortium dans la raffinerie",
        it: "Deposita il Cortium nella raffineria",
      },
      type: "10",
    },
  ],
  [
    "198",
    {
      metagame_event_id: "198",
      name: {
        de: "Maximaler Druck",
        en: "Maximum Pressure",
        es: "Presión máxima",
        fr: "Pression Maximum",
        it: "Pressione massima",
      },
      description: {
        de: "Eliminiere so viele Gegner wie möglich",
        en: "Kill as many enemies as possible",
        es: "Mata tantos enemigos como puedas.",
        fr: "Tuez autant d'ennemis que possible",
        it: "Uccidi più nemici possibili",
      },
      type: "6",
    },
  ],
  [
    "199",
    {
      metagame_event_id: "199",
      name: {
        de: "Maximaler Druck",
        en: "Maximum Pressure",
        es: "Presión máxima",
        fr: "Pression Maximum",
        it: "Pressione massima",
      },
      description: {
        de: "Eliminiere so viele Gegner wie möglich",
        en: "Kill as many enemies as possible",
        es: "Mata tantos enemigos como puedas.",
        fr: "Tuez autant d'ennemis que possible",
        it: "Uccidi più nemici possibili",
      },
      type: "6",
    },
  ],
  [
    "200",
    {
      metagame_event_id: "200",
      name: {
        de: "Maximaler Druck",
        en: "Maximum Pressure",
        es: "Presión máxima",
        fr: "Pression Maximum",
        it: "Pressione massima",
      },
      description: {
        de: "Eliminiere so viele Gegner wie möglich",
        en: "Kill as many enemies as possible",
        es: "Mata tantos enemigos como puedas.",
        fr: "Tuez autant d'ennemis que possible",
        it: "Uccidi più nemici possibili",
      },
      type: "6",
    },
  ],
  [
    "201",
    {
      metagame_event_id: "201",
      name: {
        de: "Maximaler Druck",
        en: "Maximum Pressure",
        es: "Presión máxima",
        fr: "Pression Maximum",
        it: "Pressione massima",
      },
      description: {
        de: "Eliminiere so viele Gegner wie möglich",
        en: "Kill as many enemies as possible",
        es: "Mata tantos enemigos como puedas.",
        fr: "Tuez autant d'ennemis que possible",
        it: "Uccidi più nemici possibili",
      },
      type: "6",
    },
  ],
  [
    "204",
    {
      metagame_event_id: "204",
      name: {
        de: "TEAM-KRIEG",
        en: "OUTFIT WARS",
        es: "GUERRA DE BRIGADAS",
        fr: "GUERRES D'UNITÉS",
        it: "GUERRA DELLE OUTFIT",
      },
      description: {
        de: "Erobere aktive Vanu-Relikte",
        en: "Capture Active Vanu Relics",
        es: "Captura reliquias de Vanu activas",
        fr: "Capturer les reliques Vanu actives",
        it: "Cattura le reliquie Vanu attive",
      },
      type: "10",
    },
  ],
  [
    "205",
    {
      metagame_event_id: "205",
      name: {
        de: "TEAM-KRIEG (pre-match)",
        en: "OUTFIT WARS (pre-match)",
        es: "GUERRA DE BRIGADAS (precombate)",
        fr: "GUERRES D'UNITÉS (avant-match)",
        it: "GUERRA DELLE OUTFIT (pre-partita)",
      },
      description: {
        de: "Mach dich bereit für den Team-Krieg!",
        en: "Prepare for the Outfit War!",
        es: "¡Prepárate para la guerra de brigadas!",
        fr: "Préparez-vous pour la Guerre d'Unités !",
        it: "Preparatevi alla guerra delle outfit!",
      },
      type: "4",
    },
  ],
  [
    "206",
    {
      metagame_event_id: "206",
      name: {
        de: "TEAM-KRIEG",
        en: "OUTFIT WARS",
        es: "GUERRA DE BRIGADAS",
        fr: "GUERRES D'UNITÉS",
        it: "GUERRA DELLE OUTFIT",
      },
      description: {
        de: "Aktive Relikte wechseln.",
        en: "Active Relics Changing",
        es: "Cambio de reliquias activas",
        fr: "Changement de reliques actif",
        it: "Cambiamento delle reliquie attive",
      },
      type: "10",
    },
  ],
  [
    "207",
    {
      metagame_event_id: "207",
      name: {
        de: "TEAM-KRIEG",
        en: "OUTFIT WARS",
        es: "GUERRA DE BRIGADAS",
        fr: "GUERRES D'UNITÉS",
        it: "GUERRA DELLE OUTFIT",
      },
      description: {
        de: "Erreiche 750 Punkte oder habe die meisten, wenn die Zeit abläuft.",
        en: "Earn 750 points or have the most when time expires.",
        es: "Consigue 750 puntos o ten más que nadie al acabar el tiempo.",
        fr: "Obtenez 750 points ou ayez le maximum une fois le temps écoulé.",
        it: "Ottieni 750 punti o possiedi il massimo dei punti quando scade il timer.",
      },
      type: "10",
    },
  ],
  [
    "208",
    {
      metagame_event_id: "208",
      name: {
        de: "Koltyr-Befreiung",
        en: "Koltyr Liberation",
        es: "Liberación de Koltyr",
        fr: "Libération de Koltyr",
        it: "Liberazione di Koltyr",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Koltyr zu sperren.",
        en: "Control territory to lock Koltyr",
        es: "Control del territorio para bloquear Koltyr",
        fr: "Contrôlez le territoire pour verrouiller Koltyr",
        it: "Controlla il territorio per bloccare Koltyr",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "209",
    {
      metagame_event_id: "209",
      name: {
        de: "Koltyr-Überlegenheit",
        en: "Koltyr Superiority",
        es: "Superioridad de Koltyr",
        fr: "Supériorité de Koltyr",
        it: "Superiorità di Koltyr",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Koltyr zu sperren.",
        en: "Control territory to lock Koltyr",
        es: "Control del territorio para bloquear Koltyr",
        fr: "Contrôlez le territoire pour verrouiller Koltyr",
        it: "Controlla il territorio per bloccare Koltyr",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
  [
    "210",
    {
      metagame_event_id: "210",
      name: {
        de: "Koltyr-Erleuchtung",
        en: "Koltyr Enlightenment",
        es: "Iluminación de Koltyr",
        fr: "Savoir de Koltyr",
        it: "Chiarimento di Koltyr",
      },
      description: {
        de: "Kontrolliere das Gebiet, um Koltyr zu sperren.",
        en: "Control territory to lock Koltyr",
        es: "Control del territorio para bloquear Koltyr",
        fr: "Contrôlez le territoire pour verrouiller Koltyr",
        it: "Controlla il territorio per bloccare Koltyr",
      },
      type: "9",
      experience_bonus: "25",
    },
  ],
]);
